version: 2
jobs:
  build:
    docker:
      - image: tonyodell/rakudo-nightly:latest
        environment:
          XOOS_TEST: mysql://user:passw0rd@127.0.0.1/test_db
      - image: circleci/mysql:8.0.4
        environment:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: passw0rd

    working_directory: ~

    steps:
      - checkout
      - run: 
          name: install build deps
          command: |
              apt install -y default-mysql-client libmysqlclient-dev
              zef update
              zef install --deps-only .
      - run:
          name: setup db
          command: |
              mysql -h 127.0.0.1 -u user -ppassw0rd test_db < ./sql/tests.sql
      - run:
          name: test 
          command: |
              find t -type f | egrep '\.t$' | xargs -n 1 perl6 -Ilib 
              zef test .
